name: CI

on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Extract libs from archives
      run: |
        7z x -y lib.7z
        tar -xf dx9sdk.zip
        tar -xf public.zip
        tar -xf thirdparty.zip
        tar -xf tier0.zip
        tar -xf vscript.zip
        cd lib
        tar -xf win32.zip
    - name: Clear some directories for artifacts
      run: |
        rm csgo/bin/* -Include *.dll
        rm bin/* -Include *.dll
    # https://github.com/actions/virtual-environments/issues/842#issuecomment-643382166
    - name: Install Windows 8.1 SDK
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
        Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
    - uses: microsoft/setup-msbuild@v1.0.3
    - name: Build
      run: |
        msbuild /m /t:Build /p:Configuration=Release game/client/client_csgo.vcxproj
        msbuild /m /t:Build /p:Configuration=Release game/server/server_csgo.vcxproj
        msbuild /m /t:Build /p:Configuration=Release engine/engine.vcxproj
    - name: Move builded DLLs into specific directories
      run: |
        mv game/client/Release_csgo/client.dll .\csgo\bin
        mv game/client/Release_csgo/client.pdb .\csgo\bin
        mv game/server/Release_csgo/server.dll .\csgo\bin
        mv game/server/Release_csgo/server.pdb .\csgo\bin
        mv engine/Release/engine.dll .\bin
        mv engine/Release/engine.pdb .\bin
    - uses: actions/upload-artifact@v3
      with:
        name: cstrike15_src-CI
        path: |
          csgo
          bin
